### PR TITLE
[Fix] Endurant type mapping to gufo

### PR DESCRIPTION
**Pull request by blcham**

### CODE REVIEW

**Review by psiotwo — APPROVED** [review]
lgtm

**Comment by blcham** [comment]
Don't have permission :(

"You’re not authorized to merge this pull request."

**Comment by psiotwo** [comment]
> Don't have permission :(
> 
> "You’re not authorized to merge this pull request."

Try now - the permissions are strange - ordering of authorization rules maybe matters, so I tried to reshuffle them.

**Comment by blcham** [comment]
still cannot merge :( 

Selection_367

**Comment by psiotwo** [comment]
and now?

**Comment by blcham** [comment]
huraaa ;)

**Pull request merged**
